import logging
import time
import sys
from pathlib import Path
from fastapi import FastAPI, UploadFile, File, HTTPException, BackgroundTasks, Header, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uuid
import os
from starlette.concurrency import run_in_threadpool
import json

from src.ws_manager import manager
from app.services.s3_service import upload_image_to_s3
from app.services.database import (
    create_evaluation_document, complete_evaluation,
    fail_evaluation, save_hitl_response,
    update_wireframe, get_evaluation,
    get_user_evaluations, get_evaluations_for_analysis,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger(__name__)

ROOT_DIR = Path(__file__).resolve().parent.parent
SRC_DIR  = ROOT_DIR / "src"
sys.path.append(str(SRC_DIR))

from ux_feedback_crew.crew_pipeline import run_full_ux_pipeline_raw, run_wireframe_regen_raw

app = FastAPI()
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_credentials=True,
                   allow_methods=["*"], allow_headers=["*"])
os.makedirs("outputs", exist_ok=True)
OUTPUT_DIR = Path("data/outputs")

def _load_feedback_json(evaluation_id: str) -> dict | None:
    """
    Reads the structured feedback JSON generated by the feedback tool.
    """
    json_path = OUTPUT_DIR / f"feedback_{evaluation_id}.json"
    if not json_path.exists():
        logger.warning(f"[FEEDBACK JSON] File not found: {json_path}")
        return None

    try:
        with open(json_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        logger.error(f"[FEEDBACK JSON] Failed to read {json_path}: {e}")
        return None


# ─── Models ───────────────────────────────────────────────────────────────────

class HITLFeedbackRequest(BaseModel):
    evaluation_id: str
    agent_name: str                  # "feedback_specialist" | "wireframe_designer"
    ai_suggestion: str = ""
    user_action: str                 # "agree" | "disagree" | "modify"
    user_modified_suggestion: str = ""


class WireframeRegenRequest(BaseModel):
    feedback_user_comment: str = ""   # what user said about feedback report
    wireframe_user_comment: str = ""  # what user said about wireframe


# ─── Full Pipeline ────────────────────────────────────────────────────────────

@app.post("/analyze-and-wireframe-s3/{client_id}")
async def analyze_and_wireframe_s3(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(...),
    client_id: str = "",
    x_user_id: str = Header(default="anonymous"),
):
    job_id = str(uuid.uuid4())
    pipeline_start = time.time()
    try:
        logger.info(f"[JOB START] {job_id} | user: {x_user_id}")
        await manager.send_progress(client_id, "Uploading image to S3...", 5)
        image_url = await upload_image_to_s3(file)
        create_evaluation_document(evaluation_id=job_id, user_id=x_user_id, screenshot_url=image_url)
        await manager.send_progress(client_id, "Initializing Agents...", 10)
        result = await run_in_threadpool(run_full_ux_pipeline_raw, image_url, client_id, job_id)
        duration = time.time() - pipeline_start
        logger.info(f"[PIPELINE] Completed in {duration:.2f}s")
        complete_evaluation(evaluation_id=job_id, tasks_output=result.tasks_output, pipeline_duration_seconds=duration)
        await manager.send_progress(client_id, "Pipeline Complete", 100)

        # tasks_output[2].raw is the markdown string returned directly by generate_feedback
        feedback_md = str(result.tasks_output[2].raw)
        feedback_json = _load_feedback_json(job_id)

        return {
            "evaluation_id": job_id,
            "image_url": image_url,
            "feedback": feedback_md,          # readable markdown
            "feedback_json": feedback_json,   # structured JSON for frontend
            "wireframe": str(result.tasks_output[3].raw),
        }
    
    except Exception as e:
        fail_evaluation(job_id, str(e))
        logger.error(f"[ERROR] {job_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# ─── Wireframe Regeneration ───────────────────────────────────────────────────

@app.post("/regenerate-wireframe/{evaluation_id}/{client_id}")
async def regenerate_wireframe(
    evaluation_id: str,
    client_id: str,
    body: WireframeRegenRequest,
    x_user_id: str = Header(default="anonymous"),
):
    """
    Reruns ONLY the wireframe agent.
    Called after user submits both HITL reviews (feedback + wireframe).

    Uses cached vision + heuristic + original feedback from MongoDB.
    Passes user's comments on both agents as context for improvement.
    """
    doc = get_evaluation(evaluation_id)
    if not doc:
        raise HTTPException(status_code=404, detail="Evaluation not found")

    ai = doc.get("ai_results", {})
    vision_analysis      = ai.get("vision_analysis", "")
    heuristic_evaluation = ai.get("heuristic_evaluation", {}).get("raw_text", "")
    original_feedback = ai.get("feedback_report", {}).get("markdown", "") \
                        or ai.get("feedback_report", {}).get("raw_text", "")
    image_url            = doc.get("input", {}).get("screenshot_url", "")

    if not vision_analysis:
        raise HTTPException(status_code=400, detail="Vision analysis missing from evaluation")

    logger.info(f"[REGEN] Starting wireframe regen for {evaluation_id}")
    await manager.send_progress(client_id, "Regenerating wireframe...", 10)

    try:
        result = await run_in_threadpool(
            run_wireframe_regen_raw,
            client_id,
            evaluation_id,
            vision_analysis,
            heuristic_evaluation,
            original_feedback,
            body.feedback_user_comment,
            body.wireframe_user_comment,
        )

        new_wireframe = str(result.tasks_output[0].raw)

        # Update wireframe in MongoDB
        update_wireframe(
            evaluation_id=evaluation_id,
            new_wireframe=new_wireframe,
            feedback_comment=body.feedback_user_comment,
            wireframe_comment=body.wireframe_user_comment,
            regenerated_by=x_user_id,
        )

        await manager.send_progress(client_id, "Wireframe Regenerated", 100)
        logger.info(f"[REGEN] Done for {evaluation_id}")

        return {"evaluation_id": evaluation_id, "wireframe": new_wireframe}

    except Exception as e:
        logger.error(f"[REGEN ERROR] {evaluation_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# ─── Save HITL Review ─────────────────────────────────────────────────────────

@app.post("/submit-feedback")
async def submit_hitl_feedback(
    body: HITLFeedbackRequest,
    x_user_id: str = Header(default="anonymous"),
):
    """Saves user review to MongoDB. No pipeline blocking."""
    if body.user_action not in ["agree", "disagree", "modify"]:
        raise HTTPException(status_code=400, detail="user_action must be: agree | disagree | modify")
    save_hitl_response(
        evaluation_id=body.evaluation_id,
        agent_name=body.agent_name,
        ai_suggestion=body.ai_suggestion,
        user_action=body.user_action,
        user_modified_suggestion=body.user_modified_suggestion,
        reviewed_by=x_user_id,
    )
    logger.info(f"[HITL] {body.agent_name} | {body.user_action} | {body.evaluation_id}")
    return {"message": "Feedback saved", "evaluation_id": body.evaluation_id}


# ─── Fetch ────────────────────────────────────────────────────────────────────

@app.get("/evaluation/{evaluation_id}")
async def get_single_evaluation(evaluation_id: str):
    doc = get_evaluation(evaluation_id)
    if not doc:
        raise HTTPException(status_code=404, detail="Evaluation not found")
    return doc

@app.get("/evaluations/user/{user_id}")
async def get_user_history(user_id: str):
    return {"evaluations": get_user_evaluations(user_id)}

@app.get("/evaluations/analysis/export")
async def export_for_analysis():
    docs = get_evaluations_for_analysis()
    return {"total": len(docs), "evaluations": docs}

@app.websocket("/ws/{client_id}")
async def websocket_endpoint(websocket: WebSocket, client_id: str):
    await manager.connect(client_id, websocket)
    logger.info(f"[WS] Connected: {client_id}")
    try:
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        manager.disconnect(client_id)
        logger.info(f"[WS] Disconnected: {client_id}")